services:
  postgres:
    image: postgres:15
    container_name: gistgarden_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gistgarden
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: gistgarden_redis
    ports:
      - "56379:6379"

volumes:
  pgdata: